### ISSUE TITLE
Unable to import BlocProvider

### ISSUE THREAD

**Issue by livingmine** [felangel/sealed_flutter_bloc#5] opened 2019-11-17 03:33 UTC
**Describe the bug**
Unable to import BlocProvider.

**To Reproduce**
Empty project with sealed_flutter_bloc as the only bloc related packages in pubspec.yaml.

**Expected behavior**
As this package depends on bloc, flutter, flutter_bloc and sealed_unions, i expect BlocProvider from flutter_bloc to be present, i.e., i don't have to also include the flutter_bloc package in my pubspec.yaml.

**Screenshots**

**Logs **
Run `flutter analyze` and attach any output of that command below.
If there are any analysis errors, try resolving them before filing this issue.

Paste the output of running `flutter doctor -v` here.

**Additional context**

**Comment by felangel** [comment] 2019-11-20 06:38
Hi @livingmine 👋 
Thanks for opening an issue!

Currently this is how most packages work. For example, even though `flutter_redux` depends on `redux` you still have to import `package:redux/redux.dart` independently of `flutter_redux`. Same thing applies to `flutter_bloc` and `bloc`, etc...

I'd rather leave them as separate imports because otherwise I feel it could become confusing if multiple packages export the same classes. You don't have to add `flutter_bloc` to your `pubspec.yaml`, all you need to do is add the import statement at the top of your file.

Let me know what you think 👍

**Comment by livingmine** [comment] 2019-11-20 16:22
Hi @felangel , importing flutter_bloc at the top of my file without also adding them to the pubspec.yaml does not work the way you described i.e., still unable to import BlocProvider. Am i missing something?

**Comment by felangel** [comment] 2019-11-20 19:57
@livingmine can you please share a link to a sample project which reproduces the issue? Thanks!

**Comment by felangel** [comment] 2020-03-02 00:30
Closing for now since there is no sample project to reproduce the issue. Feel free to provide a link to a sample app and I'm happy to continue the conversation 👍

**Closed by felangel** 2020-03-02 00:30 UTC
Labels: question, waiting for response
